/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;

import java.io.File;
import java.io.FileNotFoundException;
import java.net.URISyntaxException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws FileNotFoundException, URISyntaxException {
        if (args.length < 3) {
            System.out.println("Usage: search <pattern> <file>. Please try again.");
            return;
        }

        Scanner scan = new Scanner(getFile(args[2]));

        while (scan.hasNextLine()) {
            var next = scan.nextLine();
            
            if(next.contains(" " + args[1] + " ")) {
                System.out.println(next);
                System.out.println("");
            }
        }
        
        scan.close();

    }

    private static File getFile(String file) throws URISyntaxException {
        return new File(App.class.getClassLoader().getResource(file).toURI());
    }
}
